name: dependency_manipulator
description: Manipulate you Dependencies as a Game.
version: 0.0.1
homepage: https://github.com/kareemradwan/DependencyManipulator

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  xml: ^5.4.0
  yaml_edit: ^2.1.0
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0


